### ISSUE TITLE
creation of controller: Leave

### ISSUE THREAD

**Issue by meganjacobs** [meganjacobs/EmployeeTimeManagementSystem#138]
Get the updated GITHUB repository from upstream master
Implement a controller for the Leave service with TDD.
Make sure your controller(s) is/are in the right packages.
Update your repository on GITHUB with the new code.
Send (using pull request) your code to the group lead.

**Comment by anongxa** [comment]
Received thank you

**Comment by meganjacobs** [comment]
LeaveController and LeaveControllerTest created
commit: bb745305efe41dd47b4f6c2e555b2b82461e2a60
